name: Feature request
description: An idea for Jarvis
labels: ["enhancement"]
body:
  - type: textarea
    id: problema
    attributes:
      label: What problem it solves
    validations:
      required: true
  - type: textarea
    id: propuesta
    attributes:
      label: Proposal
    validations:
      required: true
